import { fetchWithAuth } from '../api/client';

export type PushPermissionState =
  | 'NOT_SUPPORTED'
  | 'DEFAULT'
  | 'GRANTED'
  | 'DENIED'
  | 'SUBSCRIBED'
  | 'ERROR';

/**
 * Convert a base64 string to a Uint8Array for PushManager subscription
 */
export function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = window.atob(base64);
  const outputArray = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) {
    outputArray[i] = rawData.charCodeAt(i);
  }
  return outputArray;
}

/**
 * Check if the browser supports Web Push and Service Workers
 */
export function isPushNotificationSupported(): boolean {
  return (
    typeof window !== 'undefined' &&
    'serviceWorker' in navigator &&
    'PushManager' in window &&
    'Notification' in window
  );
}

/**
 * Get current browser notification permission
 */
export function getBrowserNotificationPermission(): NotificationPermission | 'unsupported' {
  if (!isPushNotificationSupported()) {
    return 'unsupported';
  }
  return Notification.permission;
}

/**
 * Ensure the service worker is registered and returns the registration
 */
export async function ensureServiceWorkerRegistration(): Promise<ServiceWorkerRegistration> {
  if (!('serviceWorker' in navigator)) {
    throw new Error('Service Worker is not supported by this browser');
  }

  let registration = await navigator.serviceWorker.getRegistration();
  if (!registration) {
    registration = await navigator.serviceWorker.register('/sw.js', { scope: '/' });
  }

  await navigator.serviceWorker.ready;
  return registration;
}

/**
 * Fetch VAPID public key from backend
 */
export async function getVapidPublicKey(): Promise<string> {
  try {
    const res = await fetchWithAuth('/notifications/push/public-key');
    if (res && res.publicKey) {
      return res.publicKey;
    }
  } catch (err) {
    console.warn('[PushManager] Failed to fetch public key from backend:', err);
  }

  // Fallback to environment variable if configured
  return import.meta.env.VITE_VAPID_PUBLIC_KEY || '';
}

/**
 * Request permission and subscribe the user to Web Push
 */
export async function subscribeToPushNotifications(): Promise<{
  success: boolean;
  state: PushPermissionState;
  error?: string;
}> {
  if (!isPushNotificationSupported()) {
    return { success: false, state: 'NOT_SUPPORTED', error: 'Web Push is not supported on this browser' };
  }

  try {
    // 1. Explicitly request browser notification permission
    const permission = await Notification.requestPermission();
    if (permission === 'denied') {
      return { success: false, state: 'DENIED', error: 'Notifications are blocked in your browser' };
    }
    if (permission !== 'granted') {
      return { success: false, state: 'DEFAULT' };
    }

    // 2. Ensure service worker is registered
    const registration = await ensureServiceWorkerRegistration();

    // 3. Fetch VAPID public key
    const publicKey = await getVapidPublicKey();
    if (!publicKey) {
      throw new Error('VAPID public key could not be retrieved from the server');
    }

    // 4. Subscribe to PushManager
    const convertedKey = urlBase64ToUint8Array(publicKey);
    let subscription = await registration.pushManager.getSubscription();

    if (!subscription) {
      subscription = await registration.pushManager.subscribe({
        userVisibleOnly: true,
        applicationServerKey: convertedKey as unknown as BufferSource,
      });
    }

    // 5. Send subscription payload to backend
    const jsonSub = subscription.toJSON();
    if (!jsonSub.endpoint || !jsonSub.keys) {
      throw new Error('Invalid subscription generated by browser');
    }

    const device = /android/i.test(navigator.userAgent)
      ? 'Android'
      : /iphone|ipad|ipod/i.test(navigator.userAgent)
      ? 'iOS'
      : 'Desktop';

    await fetchWithAuth('/notifications/push/subscribe', {
      method: 'POST',
      body: JSON.stringify({
        endpoint: jsonSub.endpoint,
        keys: {
          p256dh: jsonSub.keys.p256dh,
          auth: jsonSub.keys.auth,
        },
        userAgent: navigator.userAgent,
        device,
      }),
    });

    return { success: true, state: 'SUBSCRIBED' };
  } catch (err: any) {
    console.error('[PushManager] Subscription error:', err);
    return { success: false, state: 'ERROR', error: err?.message || 'Failed to enable notifications' };
  }
}

/**
 * Unsubscribe current device from Web Push
 */
export async function unsubscribeFromPushNotifications(): Promise<{
  success: boolean;
  state: PushPermissionState;
}> {
  if (!isPushNotificationSupported()) {
    return { success: false, state: 'NOT_SUPPORTED' };
  }

  try {
    const registration = await ensureServiceWorkerRegistration();
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      const endpoint = subscription.endpoint;
      await subscription.unsubscribe();

      await fetchWithAuth('/notifications/push/unsubscribe', {
        method: 'DELETE',
        body: JSON.stringify({ endpoint }),
      }).catch((e) => console.warn('[PushManager] Backend unsubscribe error:', e));
    }

    return { success: true, state: 'DEFAULT' };
  } catch (err) {
    console.error('[PushManager] Unsubscribe error:', err);
    return { success: false, state: 'ERROR' };
  }
}

/**
 * Check overall push status (combining browser permission and active subscription)
 */
export async function getPushNotificationStatus(): Promise<PushPermissionState> {
  if (!isPushNotificationSupported()) {
    return 'NOT_SUPPORTED';
  }

  const permission = Notification.permission;
  if (permission === 'denied') {
    return 'DENIED';
  }
  if (permission === 'default') {
    return 'DEFAULT';
  }

  try {
    const registration = await ensureServiceWorkerRegistration();
    const subscription = await registration.pushManager.getSubscription();

    if (subscription) {
      return 'SUBSCRIBED';
    } else {
      return 'GRANTED';
    }
  } catch (err) {
    return 'ERROR';
  }
}

/**
 * Automatically sync/register push subscription if permission was already granted in this browser
 */
export async function syncPushSubscriptionIfGranted(): Promise<void> {
  if (!isPushNotificationSupported()) return;

  if (Notification.permission === 'granted') {
    try {
      const registration = await ensureServiceWorkerRegistration();
      const existingSub = await registration.pushManager.getSubscription();

      if (!existingSub) {
        // Permission was granted but no subscription exists (e.g. fresh session or reset)
        // Subscribing now without prompting permission popup because it's already granted
        const publicKey = await getVapidPublicKey();
        if (publicKey) {
          const convertedKey = urlBase64ToUint8Array(publicKey);
          const newSub = await registration.pushManager.subscribe({
            userVisibleOnly: true,
            applicationServerKey: convertedKey as unknown as BufferSource,
          });

          const jsonSub = newSub.toJSON();
          if (jsonSub.endpoint && jsonSub.keys) {
            const device = /android/i.test(navigator.userAgent)
              ? 'Android'
              : /iphone|ipad|ipod/i.test(navigator.userAgent)
              ? 'iOS'
              : 'Desktop';

            await fetchWithAuth('/notifications/push/subscribe', {
              method: 'POST',
              body: JSON.stringify({
                endpoint: jsonSub.endpoint,
                keys: {
                  p256dh: jsonSub.keys.p256dh,
                  auth: jsonSub.keys.auth,
                },
                userAgent: navigator.userAgent,
                device,
              }),
            });
          }
        }
      }
    } catch (err) {
      console.warn('[PushManager] Background sync warning:', err);
    }
  }
}
